# Generated by Django 2.0.7 on 2019-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(choices=[('I', 'Inventory'), ('R', 'Remittances'), ('M', 'Members'), ('N', 'Maintenance')], max_length=1)),
                ('description', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
