# Generated by Django 2.0.7 on 2018-11-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('I', 'Inventory'), ('R', 'Remittances'), ('M', 'Members'), ('N', 'Maintenance')], max_length=1),
        ),
    ]
