# Generated by Django 2.0.7 on 2018-11-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181119_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
