# Generated by Django 2.0.5 on 2018-07-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('route', models.CharField(choices=[('M', 'Main Road'), ('R', 'Right Route'), ('L', 'Left Route')], max_length=1)),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('F', 'Finished')], max_length=1)),
                ('a_range_from', models.IntegerField()),
                ('a_range_to', models.IntegerField()),
                ('b_range_from', models.IntegerField()),
                ('b_range_to', models.IntegerField()),
                ('c_range_from', models.IntegerField()),
                ('c_range_to', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemittanceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('fuel_cost', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('other_cost', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=1)),
                ('a_end', models.IntegerField()),
                ('a_total', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('b_end', models.IntegerField()),
                ('b_total', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('c_end', models.IntegerField()),
                ('c_total', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('total', models.DecimalField(decimal_places=10, max_digits=19)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remittances.Deployment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(choices=[('A', 'AM Shift'), ('P', 'PM Shift'), ('M', 'Midnight Shift')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoidTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('ticket_number', models.CharField(max_length=64)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remittances.Deployment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remittances.Shift'),
        ),
    ]
