# Generated by Django 2.0.7 on 2018-07-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeptransaction',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remittances.BeepShift'),
        ),
    ]
