# Generated by Django 2.0.6 on 2018-07-05 06:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('remittances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('range_from', models.IntegerField()),
                ('range_to', models.IntegerField()),
                ('type', models.CharField(choices=[('A', '9 Pesos'), ('B', '11 Pesos'), ('C', '14 Pesos')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('end_ticket', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('assigned_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remittances.AssignedTicket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriversAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='a_range_from',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='a_range_to',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='b_range_from',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='b_range_to',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='c_range_from',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='c_range_to',
        ),
        migrations.RemoveField(
            model_name='remittanceform',
            name='a_end',
        ),
        migrations.RemoveField(
            model_name='remittanceform',
            name='a_total',
        ),
        migrations.RemoveField(
            model_name='remittanceform',
            name='b_end',
        ),
        migrations.RemoveField(
            model_name='remittanceform',
            name='b_total',
        ),
        migrations.RemoveField(
            model_name='remittanceform',
            name='c_end',
        ),
        migrations.RemoveField(
            model_name='remittanceform',
            name='c_total',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
        migrations.RemoveField(
            model_name='voidticket',
            name='deployment',
        ),
        migrations.AddField(
            model_name='shift',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 5, 6, 15, 10, 844677, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 5, 6, 15, 16, 194222, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voidticket',
            name='ticket_number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='driversassigned',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remittances.Shift'),
        ),
        migrations.AddField(
            model_name='consumedticket',
            name='remittance_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remittances.RemittanceForm'),
        ),
        migrations.AddField(
            model_name='assignedticket',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remittances.Deployment'),
        ),
        migrations.AddField(
            model_name='voidticket',
            name='assigned_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='remittances.AssignedTicket'),
            preserve_default=False,
        ),
    ]
