# Generated by Django 2.0.7 on 2018-07-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedticket',
            name='type',
            field=models.CharField(choices=[('A', '10 Pesos'), ('B', '12 Pesos'), ('C', '15 Pesos')], max_length=1),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('O', 'Ongoing'), ('F', 'Finished')], default='O', max_length=1),
        ),
    ]
