# Generated by Django 2.0.6 on 2018-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittanceform',
            name='km_from',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='remittanceform',
            name='km_to',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
