# Generated by Django 2.0.7 on 2018-07-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0002_auto_20180712_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversassigned',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_name', to='members.Driver'),
        ),
    ]
