# Generated by Django 2.0.6 on 2018-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
