# Generated by Django 2.0.7 on 2018-07-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='itemmovement',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
