# Generated by Django 2.0.7 on 2018-07-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('NM', 'Needs Maintenance'), ('UM', 'Under Maintenance')], default='A', max_length=2),
            preserve_default=False,
        ),
    ]
