# Generated by Django 2.0.6 on 2018-07-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
