# Generated by Django 2.0.7 on 2018-07-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
