# Generated by Django 2.0.7 on 2018-07-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180717_0642'),
        ('inventory', '0003_auto_20180712_1308'),
    ]

    operations = [
    ]
