# Generated by Django 2.0.5 on 2018-07-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180709_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, default='client/src/images/users.png', null=True, upload_to=''),
        ),
    ]
