# Generated by Django 2.0.7 on 2018-07-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180709_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(default='client/src/images/users.png', null=True, upload_to=''),
        ),
    ]
